---
- name: Initialize Kubernetes cluster
  command: >
    kubeadm init
    --pod-network-cidr={{ pod_network_cidr }}
    --service-cidr={{ service_cidr }}
    --apiserver-advertise-address={{ ansible_default_ipv4.address }}
    --control-plane-endpoint={{ ansible_default_ipv4.address }}
  register: kubeadm_init
  when: not kubeadm_initialized.stat.exists

- name: Create .kube directory
  file:
    path: /home/{{ system_user }}/.kube
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"

- name: Copy admin.conf to user config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ system_user }}/.kube/config
    remote_src: yes
    owner: "{{ system_user }}"
    group: "{{ system_user }}"

- name: Install Calico network plugin
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Save join command to file
  copy:
    content: "{{ join_command.stdout }}"
    dest: /tmp/join-command.sh
    mode: '0755'
